version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/chartbrew

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: npm run setup

      - save_cache:
          paths:
            - node_modules
            - client/node_modules
            - client/src/semantic/tasks
            - client/src/semantic/src
            - server/node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

  # lint the client project
  lint1:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/chartbrew
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Linting client code
          command: cd client/src/semantic && npx gulp build && cd ../../ && npm run lint

  # lint the server project
  lint2:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/chartbrew
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Linting server code
          command: cd server && npm run lint

  build1:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/chartbrew
    # Build the client
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Building the client
          command: cd client && npm run build

  build2:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/chartbrew
    # build the docs
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Building the docs
          command: npm run docs:build

workflows:
  version: 2
  setup_and_build:
    jobs:
      - setup
      - lint1:
          requires:
            - setup
      - lint2:
          requires:
            - setup
      - build1:
          requires:
            - setup
      - build2:
          requires:
            - setup
